// ------------------------------------------------------------------
// tests/checks/knowledge-drift.test.js - Keeps what the system was
// told from quietly decaying.
//
// The other gates check STRUCTURE. render-coverage proves a stored
// value renders somewhere; knowledge-links proves the vocabulary is
// documented; reference-drift proves the reference matches the code.
// None of them notices a note that lost its anchor, a term whose
// source was dropped, or a closed item whose resolution went missing.
// Those are the failures that matter most to whoever supplies the
// content, because the promise they are relying on is that what they
// say does not get lost. Twenty orphan notes existed for weeks and
// nothing failed.
//
// Like the reference gate this is a RATCHET, not a zero-tolerance
// check: 80 items have no summary today, so a gate demanding zero
// could not be switched on until the work was done, which is exactly
// when a gate stops being useful. tests/knowledge-budget.json declares
// the ceiling; fixing rows lowers it in the same commit.
//
// Five figures ARE at zero, and those are the ones worth watching.
// Every glossary term has a definition and a source, every journey
// stage has a source, every document has a digest, and no finding
// claims a promotion with nothing behind it. Each is a promise being
// kept. This is what makes breaking one of them fail the build.
// ------------------------------------------------------------------
"use strict";
const test = require("node:test");
const assert = require("node:assert/strict");
const { read, trackedFiles } = require("../lib/repo.js");
const { RULES } = require("../../scripts/gen-knowledge.js");

const ARTEFACT = "supabase/knowledge-coverage.json";
const coverage = JSON.parse(read(ARTEFACT));
const budget = JSON.parse(read("tests/knowledge-budget.json"));

test("the artefact is present and says it is generated", () => {
  assert.match(coverage.generated_note, /GENERATED by scripts\/gen-knowledge\.js/,
    "it must say so, so nobody hand-edits it");
  assert.match(coverage.generated_on, /^\d{4}-\d{2}-\d{2}$/);
  assert.ok(Object.keys(coverage.figures).length > 0);
});

test("no content reaches the committed artefact, only counts", () => {
  const text = read(ARTEFACT);
  // A title, body or path leaking in would put owner-supplied content
  // and possibly a merchant name into a public repository.
  assert.doesNotMatch(text, /https?:\/\//);
  assert.doesNotMatch(text, /\/api\//);
  for (const value of JSON.stringify(coverage.figures).match(/"[^"]*"/g) || []) {
    assert.ok(/^"(n|of|pct|[a-z_]+\.[a-z_]+)"$/.test(value),
      `${value} is not a count or a rule key - the artefact carries neither`);
  }
});

test("every rule the generator declares is measured and capped", () => {
  const missing = [];
  for (const rule of RULES) {
    if (!coverage.figures[rule.key]) missing.push(`${rule.key}: not in the artefact`);
    else if (budget.figures[rule.key] === undefined) {
      missing.push(`${rule.key}: measured with no declared ceiling`);
    }
    if (!budget.notes[rule.key] || budget.notes[rule.key].length < 40) {
      missing.push(`${rule.key}: a ceiling without a note is a number nobody can act on`);
    }
  }
  assert.deepEqual(missing, [], "Knowledge budget:\n" + missing.join("\n"));
});

test("every rule states why it is a rule", () => {
  for (const rule of RULES) {
    assert.ok(rule.why && rule.why.length > 40,
      `${rule.key}: a check with no reason gets deleted by the next person who hits it`);
  }
});

test("nothing has decayed past its declared ceiling", () => {
  const failures = [];
  for (const [key, figure] of Object.entries(coverage.figures)) {
    const cap = budget.figures[key];
    if (cap === undefined) continue;
    if (figure.n > cap) {
      failures.push(`${key} rose to ${figure.n} of ${figure.of}, ceiling is ${cap}. ` +
        "Either fix the rows or raise the ceiling deliberately, saying why.");
    }
  }
  assert.deepEqual(failures, [], "Knowledge decay:\n" + failures.join("\n"));
});

test("the promises already kept are held at zero", () => {
  // These six are not a backlog. Each is a rule the content already
  // satisfies, and a rule satisfied by accident is one nobody notices
  // breaking. Holding them at zero is the whole point of the gate.
  //
  // embeddings.stale is the one that is actively misleading rather than
  // merely missing: a vector computed from text that has since changed
  // still answers searches, with the wrong meaning and no sign of it.
  for (const key of ["terms.no_definition", "terms.no_source", "stages.no_source",
    "documents.no_digest", "findings.promoted_without_item", "embeddings.stale"]) {
    assert.equal(budget.figures[key], 0,
      `${key} is at zero today and its ceiling must stay zero - raising it is ` +
      "a decision to let the guarantee lapse, not a housekeeping edit");
  }
});

test("a ceiling that has been beaten is tightened, not left slack", () => {
  // Slack is how a ratchet quietly stops ratcheting. Ten is the same
  // tolerance the reference budget uses, so the two read alike.
  const slack = [];
  for (const [key, figure] of Object.entries(coverage.figures)) {
    const cap = budget.figures[key];
    if (cap === undefined) continue;
    if (cap - figure.n > 10) {
      slack.push(`${key} is ${figure.n} against a ceiling of ${cap} - ` +
        "lower the ceiling to lock the gain in.");
    }
  }
  assert.deepEqual(slack, [], "Slack in the ratchet:\n" + slack.join("\n"));
});

test("each figure is a count of a subset, not a free-standing number", () => {
  for (const [key, figure] of Object.entries(coverage.figures)) {
    assert.ok(figure.n <= figure.of,
      `${key}: ${figure.n} of ${figure.of} - a subset cannot exceed the set it is drawn from`);
    assert.ok(figure.n >= 0 && Number.isInteger(figure.n), `${key}: not a count`);
  }
});

test("the artefact is not stale against the applied migrations", () => {
  // Same staleness rule as the reference gate: a schema change that
  // adds or drops a knowledge table invalidates the counts.
  const migrations = trackedFiles()
    .filter((f) => f.startsWith("supabase/migrations/") && f.endsWith(".sql"))
    .map((f) => f.split("/").pop().slice(0, 8))
    .sort();
  const newest = migrations[migrations.length - 1];
  const asDate = `${newest.slice(0, 4)}-${newest.slice(4, 6)}-${newest.slice(6, 8)}`;
  assert.ok(coverage.generated_on >= asDate,
    `${ARTEFACT} was generated ${coverage.generated_on}, older than migration ` +
    `${newest}. Run npm run knowledge.`);
});
