// ------------------------------------------------------------------
// tests/checks/reference-drift.test.js - Keeps the API reference from
// drifting further from the code it documents.
//
// The suite has no database access and no credentials, by design, and
// the LaunchPad source is not in this repo. So the comparison happens
// once, in a session with both (npm run coverage), into
// supabase/reference-coverage.json - counts and a digest, never a
// path - and this gate reads that artefact. Same pattern as
// supabase/schema-snapshot.json and its drift check.
//
// It is a RATCHET, not a zero-tolerance gate: 12 wrong rows and 219
// undocumented routes exist today, so a gate demanding zero could not
// be turned on until the work was finished, which is exactly when a
// gate stops being useful. tests/reference-budget.json declares the
// ceiling instead; fixing rows lowers it in the same commit.
// ------------------------------------------------------------------
"use strict";
const test = require("node:test");
const assert = require("node:assert/strict");
const { read, trackedFiles } = require("../lib/repo.js");

const ARTEFACT = "supabase/reference-coverage.json";
const coverage = JSON.parse(read(ARTEFACT));
const budget = JSON.parse(read("tests/reference-budget.json"));

// Every counted field a budget may cap. Adding one here without adding
// it to the budget file is caught by the completeness test below.
// `gap` joins them; `uncalled` and `stale_docs` deliberately do not.
// A capped figure is one a session should be driving down. How many
// routes the portal calls is a fact about the API, not a defect, and
// documented-but-uncalled RISES on purpose as the register of routes
// nothing calls lands. Capping either would make honest work fail the
// gate, which is how a ratchet teaches people to stop running it.
const CAPPED = ["phantom", "absent", "undeclared_mirrors", "duplicates",
  "unverified_badges", "gap_badges", "gap"];

test("the coverage artefact is present and shaped", () => {
  assert.match(coverage.generated_note, /GENERATED by scripts\/gen-coverage\.js/,
    "the artefact must say it is generated, so nobody hand-edits it");
  assert.match(coverage.generated_on, /^\d{4}-\d{2}-\d{2}$/);
  assert.match(coverage.source.route_digest, /^[0-9a-f]{64}$/,
    "the digest is how a session tells the API changed without a path in the repo");
  assert.ok(coverage.source.routes > 0);
  assert.ok(Object.keys(coverage.specs).length > 0);
});

test("no route path, host or payload reaches the committed artefact", () => {
  const text = read(ARTEFACT);
  assert.doesNotMatch(text, /\/api\//,
    "the artefact carries counts and a digest only - this repo is public");
  assert.doesNotMatch(text, /https?:\/\//);
});

test("every spec is inside its declared drift budget", () => {
  const failures = [];
  for (const [title, spec] of Object.entries(coverage.specs)) {
    const allowed = budget.specs[title];
    if (!allowed) {
      failures.push(`${title}: no entry in tests/reference-budget.json. ` +
        "A new spec declares its baseline in the same commit.");
      continue;
    }
    for (const field of CAPPED) {
      if (spec[field] === undefined) continue;
      const cap = allowed[field];
      if (cap === undefined) {
        failures.push(`${title}: ${field} is ${spec[field]} with no declared ceiling.`);
      } else if (spec[field] > cap) {
        failures.push(`${title}: ${field} rose to ${spec[field]}, ceiling is ${cap}. ` +
          "Either fix the rows or raise the ceiling deliberately, saying why.");
      }
    }
  }
  assert.deepEqual(failures, [], "Reference drift:\n" + failures.join("\n"));
});

test("a ceiling that has been beaten is tightened, not left slack", () => {
  // Slack ceilings are how a ratchet quietly stops ratcheting. A gap of
  // more than ten between the real figure and its ceiling means someone
  // fixed rows and did not lower the number behind them.
  const slack = [];
  for (const [title, spec] of Object.entries(coverage.specs)) {
    const allowed = budget.specs[title] || {};
    for (const field of CAPPED) {
      if (spec[field] === undefined || allowed[field] === undefined) continue;
      if (allowed[field] - spec[field] > 10) {
        slack.push(`${title}: ${field} is ${spec[field]} against a ceiling of ` +
          `${allowed[field]} - lower the ceiling to lock the gain in.`);
      }
    }
  }
  assert.deepEqual(slack, [], "Slack in the ratchet:\n" + slack.join("\n"));
});

test("every budgeted spec explains its baseline", () => {
  for (const [title, allowed] of Object.entries(budget.specs)) {
    assert.ok(allowed.note && allowed.note.length > 40,
      `${title}: a ceiling without a note is a number nobody can act on.`);
  }
});

test("a comparable spec reports its reconciliation, an incomparable one abstains", () => {
  for (const [title, spec] of Object.entries(coverage.specs)) {
    if (spec.comparable) {
      for (const field of ["routes", "matched", "phantom", "absent", "accounted_pct"]) {
        assert.equal(typeof spec[field], "number", `${title}: missing ${field}`);
      }
      assert.equal(spec.matched + spec.phantom, spec.documented,
        `${title}: every documented row is either matched or phantom`);
      assert.equal(
        spec.matched + spec.scope_variants + spec.undeclared_mirrors + spec.absent,
        spec.routes, `${title}: every route falls in exactly one bucket`);
    } else {
      assert.equal(spec.accounted_pct, undefined,
        `${title}: a spec with no source to compare against must not show a ` +
        "coverage figure - it would read as verified when it is not");
    }
  }
});

test("the consumer split is complete and adds up", () => {
  for (const [title, spec] of Object.entries(coverage.specs)) {
    if (spec.called === undefined) continue;
    assert.equal(spec.called + spec.uncalled, spec.routes,
      `${title}: every route is either called or it is not`);
    assert.ok(spec.gap <= spec.absent,
      `${title}: the gap is a subset of absent - called routes nobody wrote up`);
    assert.ok(spec.stale_docs <= spec.uncalled,
      `${title}: a stale row is a documented route nothing calls`);
  }
});

test("every documented route nothing calls is badged as such", () => {
  // This is the alignment the reference lives or dies on. The split is
  // derived on every run from the call inventory; the badge is written
  // on a row by a session. When they disagree, a reader is being told
  // something the code contradicts - a superseded route presented as
  // today's surface, or a live one flagged as dead. Neither is a
  // reading error, so neither may depend on someone remembering.
  //
  // It corrects in both directions. Document an uncalled route without
  // the badge and this fails. Wire the portal up to a badged route and
  // it fails again until the badge comes off.
  for (const [title, spec] of Object.entries(coverage.specs)) {
    if (spec.stale_docs === undefined) continue;
    assert.equal(spec.consumer_badges, spec.stale_docs,
      `${title}: ${spec.stale_docs} documented routes have no portal consumer but ` +
      `${spec.consumer_badges} carry the badge saying so. Badge the difference, or ` +
      "drop the badge from rows the portal now calls - the derived figure is right " +
      "by construction and the badge is what drifts.");
  }
});

test("the artefact is not stale against the applied migrations", () => {
  const migrations = trackedFiles()
    .filter((f) => f.startsWith("supabase/migrations/") && f.endsWith(".sql"))
    .map((f) => f.split("/").pop().slice(0, 8))
    .sort();
  const newest = migrations[migrations.length - 1];
  const asDate = `${newest.slice(0, 4)}-${newest.slice(4, 6)}-${newest.slice(6, 8)}`;
  assert.ok(coverage.generated_on >= asDate,
    `${ARTEFACT} was generated ${coverage.generated_on}, older than migration ` +
    `${newest}. Run npm run coverage - the repo describing a reference it cannot ` +
    "re-derive is how the schema lost five migrations.");
});
